-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.all_sessions
(
    full_visitor_id character varying(50) COLLATE pg_catalog."default",
    channel_grouping character varying(50) COLLATE pg_catalog."default",
    "time" integer,
    country character varying(50) COLLATE pg_catalog."default",
    city character varying(50) COLLATE pg_catalog."default",
    total_transaction_revenue integer,
    transactions integer,
    time_on_site integer,
    page_views integer,
    session_quality_dim integer,
    date date,
    visit_id integer,
    type character varying(10) COLLATE pg_catalog."default",
    product_refund_amount integer,
    product_quantity integer,
    product_price real,
    product_revenue integer,
    product_sku character varying(50) COLLATE pg_catalog."default",
    v2_product_name character varying(100) COLLATE pg_catalog."default",
    v2_product_category character varying(100) COLLATE pg_catalog."default",
    product_variant character varying(50) COLLATE pg_catalog."default",
    currency_code character varying(10) COLLATE pg_catalog."default",
    item_revenue integer,
    transaction_revenue integer,
    transaction_id character varying(50) COLLATE pg_catalog."default",
    page_title character varying(100) COLLATE pg_catalog."default",
    search_keyword character varying(100) COLLATE pg_catalog."default",
    page_path_level1 character varying(100) COLLATE pg_catalog."default",
    ecommerce_action_type integer,
    ecommerce_action_step integer,
    ecommerce_action_option character varying(50) COLLATE pg_catalog."default",
    PRIMARY KEY (full_visitor_id)
);

CREATE TABLE IF NOT EXISTS public.analytics
(
    visit_number integer,
    visit_id integer,
    visit_start_time integer,
    date date,
    full_visitor_id character varying(50) COLLATE pg_catalog."default",
    user_id integer,
    channel_grouping character varying(50) COLLATE pg_catalog."default",
    social_engagement_type character varying(50) COLLATE pg_catalog."default",
    units_sold integer,
    page_views integer,
    time_on_site integer,
    bounces integer,
    revenue bigint,
    unit_price real,
    PRIMARY KEY (full_visitor_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_sku character varying(50) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default",
    ordered_quantity integer,
    stock_level integer,
    restocking_lead_time integer,
    sentiment_score real,
    sentiment_magnitude real,
    PRIMARY KEY (product_sku)
);

CREATE TABLE IF NOT EXISTS public.sales_report
(
    product_sku character varying(50) COLLATE pg_catalog."default",
    total_ordered integer,
    ratio real,
    PRIMARY KEY (product_sku)
);

ALTER TABLE IF EXISTS public.all_sessions
    ADD FOREIGN KEY (full_visitor_id)
    REFERENCES public.analytics (full_visitor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (product_sku)
    REFERENCES public.sales_report (product_sku) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (product_sku)
    REFERENCES public.all_sessions (product_sku) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;